---
netbox_services_kiab:

  - device: 
      name: kiab
    name: node-exporter
    ports: 
      - 9100
    protocol: tcp
    ipaddresses: 
      - 172.25.5.250/32
      - 229
      - 172.25.6.250/32

  - name: DNS
    protocol: udp
    ports:
      - 53
    device:
      name: kiab
    ipaddresses:
      - 172.25.6.250

  - name: TFTP
    protocol: udp
    ports:
      - 69
    device:
      name: kiab
    ipaddresses:
      - 172.25.1.250
    custom_fields:
      Directory: /srv/tftp
      User: tftp
      Options: "--secure --create"
    description: "TFTP Server for Switch Management"
