---
netbox_ip_addresses_computers_prodk8ssvc:

  - address: "172.25.21.253/32"
    role: "VRRP"
    vrf: "prodk8ssvc"
    assigned_object_id: '{{ query("netbox.netbox.nb_lookup", "fhrp-groups",
        api_filter="group_id=2521",
        api_endpoint="http://" + netbox_loadbalancer_ip,
        token=netbox_ansible_token) | map(attribute="key") | join(",") }}'
    assigned_object_type: "ipam.fhrpgroup"

